import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={'w-full min-h-screen bg-gradient-conic from-slate-800 to-gray-700'}>
        <Navbar />
          {children}
      </body>
    </html>
  );
}
